### ISSUE TITLE
Crash in Carla when opening UI

### ISSUE THREAD

**Issue by mxmilkiib** [sjaehn/BHarvestr#1]
Coredump: https://gist.github.com/mxmilkiib/9a41b9241f644c70153ea81718cb44be

Loads the UI in Jalv though.

Not sure if this is a BHarvestr or Carla issue.

**Comment by sjaehn** [comment]
Thanks for info. Likely it is an B.Harvestr-related issue as the two top stack traces are from B.Harvestr GUI shared object. Would be nice to have a symbol and/or a code line. Therefore, may I ask you to compile it again with "-g":

make CPPFLAGS+=-g
sudo make install  PREFIX=your_lv2_directory

I tried to reproduce the bug, but on my system B.Harvestr works fine with Carla 2.0, Ardour 5.12, jalv, and zrythm. With the notable exception of it's hunger for CPU speed.

**Comment by SpotlightKid** [comment]
I can confirm this crash still happens with carla 2.2.0-RC1. Here's a backtrace I produced by compiling BHarvestr with `make CPPFLAGS+="+g "` and running carla with `carla --gdb`. Not very helpful, I'm afraid:

```
(gdb) thread apply all bt

Thread 23 (Thread 0x7fffaf2a2700 (LWP 84252)):
#0  0x00007ffff79e8158 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff6721e08 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff6720084 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 22 (Thread 0x7fffafaa3700 (LWP 84251)):
#0  0x00007ffff79e8158 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff6721e08 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff6720084 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 21 (Thread 0x7fffb8eef700 (LWP 84250)):
#0  0x00007ffff79e8158 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff6721e08 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff6720084 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 20 (Thread 0x7fffb96f0700 (LWP 84249)):
#0  0x00007ffff79e8158 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff6721e08 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff6720084 in  () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 19 (Thread 0x7fffc8400700 (LWP 84248)):
#0  0x00007ffff7e8371d in syscall () at /usr/lib/libc.so.6
#1  0x00007fffe95c63bb in  () at /usr/lib/libjack.so.0
#2  0x00007fffe95a9045 in  () at /usr/lib/libjack.so.0
#3  0x00007fffe95a8257 in  () at /usr/lib/libjack.so.0
#4  0x00007fffe95a7fd8 in  () at /usr/lib/libjack.so.0
#5  0x00007fffe95c44dd in  () at /usr/lib/libjack.so.0
#6  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 18 (Thread 0x7fffc86f5700 (LWP 84247)):
#0  0x00007ffff7e79aec in read () at /usr/lib/libc.so.6
#1  0x00007fffe95c570f in  () at /usr/lib/libjack.so.0
#2  0x00007fffe95ca30d in  () at /usr/lib/libjack.so.0
#3  0x00007fffe95ca138 in  () at /usr/lib/libjack.so.0
#4  0x00007fffe95c44dd in  () at /usr/lib/libjack.so.0
#5  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 17 (Thread 0x7fffbb7fe700 (LWP 84246)):
#0  0x00007ffff7e50571 in clock_nanosleep@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x00007ffff7e55e87 in nanosleep () at /usr/lib/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--c
#2  0x00007ffff7e80d99 in usleep () at /usr/lib/libc.so.6
#3  0x00007fffe988ef9b in  () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007fffe988e2df in  () at /usr/lib/carla/libcarla_standalone2.so
#5  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7fffbbfff700 (LWP 84245)):
#0  0x00007ffff7e50571 in clock_nanosleep@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x00007ffff7e55e87 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7e80d99 in usleep () at /usr/lib/libc.so.6
#3  0x00007fffe98e8116 in  () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007fffe988e2df in  () at /usr/lib/carla/libcarla_standalone2.so
#5  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7fffe0126700 (LWP 84244)):
#0  0x00007ffff7e8371d in syscall () at /usr/lib/libc.so.6
#1  0x00007fffe95c63bb in  () at /usr/lib/libjack.so.0
#2  0x00007fffe95a9045 in  () at /usr/lib/libjack.so.0
#3  0x00007fffe95a8257 in  () at /usr/lib/libjack.so.0
#4  0x00007fffe95a7fd8 in  () at /usr/lib/libjack.so.0
#5  0x00007fffe95c44dd in  () at /usr/lib/libjack.so.0
#6  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7fffc8ef6700 (LWP 84243)):
#0  0x00007ffff7e50571 in clock_nanosleep@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x00007ffff7e55e87 in nanosleep () at /usr/lib/libc.so.6
#2  0x00007ffff7e80d99 in usleep () at /usr/lib/libc.so.6
#3  0x00007fffe98d3c6e in  () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007fffe988e2df in  () at /usr/lib/carla/libcarla_standalone2.so
#5  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fffe030d700 (LWP 84242)):
#0  0x00007ffff7e79aec in read () at /usr/lib/libc.so.6
#1  0x00007fffe95c570f in  () at /usr/lib/libjack.so.0
#2  0x00007fffe95ca30d in  () at /usr/lib/libjack.so.0
#3  0x00007fffe95ca138 in  () at /usr/lib/libjack.so.0
#4  0x00007fffe95c44dd in  () at /usr/lib/libjack.so.0
#5  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7fffe04d2700 (LWP 84241)):
#0  0x00007ffff79e7e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffe95c4fb0 in  () at /usr/lib/libjack.so.0
#2  0x00007fffe95b90e6 in  () at /usr/lib/libjack.so.0
#3  0x00007fffe95c44dd in  () at /usr/lib/libjack.so.0
#4  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fffc96f7700 (LWP 84240)):
#0  0x00007ffff7e88f3e in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007fffe99fc9ec in  () at /usr/lib/carla/libcarla_standalone2.so
#2  0x00007fffe99fd07f in  () at /usr/lib/carla/libcarla_standalone2.so
#3  0x00007fffe99fd591 in  () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007fffe99fea7d in  () at /usr/lib/carla/libcarla_standalone2.so
#5  0x00007ffff6d19b74 in std::execute_native_thread_routine(void*) (__p=0x5555561fb960) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7fffc9ef8700 (LWP 84239)):
#0  0x00007ffff79e8488 in pthread_cond_clockwait () at /usr/lib/libpthread.so.0
#1  0x00007fffe99f0917 in  () at /usr/lib/carla/libcarla_standalone2.so
#2  0x00007ffff6d19b74 in std::execute_native_thread_routine(void*) (__p=0x555556b83f20) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#3  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fffca6f9700 (LWP 84238)):
#0  0x00007ffff7e88f3e in epoll_wait () at /usr/lib/libc.so.6
#1  0x00007fffe99fc9ec in  () at /usr/lib/carla/libcarla_standalone2.so
#2  0x00007fffe99fd07f in  () at /usr/lib/carla/libcarla_standalone2.so
#3  0x00007fffe99fd591 in  () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007fffe99fd821 in  () at /usr/lib/carla/libcarla_standalone2.so
#5  0x00007ffff6d19b74 in std::execute_native_thread_routine(void*) (__p=0x555555d40d40) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7fffcbfff700 (LWP 84237)):
#0  0x00007ffff79e7e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffe244270c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fffe2441a28 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffe0d53700 (LWP 84236)):
#0  0x00007ffff79e7e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffe244270c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fffe2441a28 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffe1554700 (LWP 84235)):
#0  0x00007ffff79e7e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffe244270c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fffe2441a28 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffe1d55700 (LWP 84234)):
#0  0x00007ffff79e7e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffe244270c in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fffe2441a28 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffe371a700 (LWP 84233)):
#0  0x00007ffff79e7e32 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff6721e84 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff209f1d3 in  () at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffe3fff700 (LWP 84232)):
#0  0x00007ffff7e7e05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff5eb6168 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff5e67221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff6959331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff68ff13c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff671ac32 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff16b7098 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffea64f700 (LWP 84231)):
#0  0x00007ffff7e7e05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff29c463b in  () at /usr/lib/libxcb.so.1
#2  0x00007ffff29c637b in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fffea9c2c51 in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff671be0f in  () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff79e1422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff7e88bf3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7883740 (LWP 84225)):
#0  0x0000441f0f66ffff in  ()
#1  0x00007fffe9949f50 in  () at /usr/lib/carla/libcarla_standalone2.so
#2  0x00007fffe9955725 in  () at /usr/lib/carla/libcarla_standalone2.so
#3  0x00007fffe989ffe7 in carla_show_custom_ui () at /usr/lib/carla/libcarla_standalone2.so
#4  0x00007ffff7f78a8d in  () at /usr/lib/libffi.so.7
#5  0x00007ffff7f7801b in  () at /usr/lib/libffi.so.7
#6  0x00007ffff728d81e in  () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#7  0x00007ffff729738f in  () at /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so
#8  0x00007ffff7b21bf4 in _PyObject_MakeTpCall () at /usr/lib/libpython3.8.so.1.0
#9  0x00007ffff7b1d4d8 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.8.so.1.0
#10 0x00007ffff7b38896 in  () at /usr/lib/libpython3.8.so.1.0
#11 0x00007ffff7b1d097 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.8.so.1.0
#12 0x00007ffff7b29138 in _PyFunction_Vectorcall () at /usr/lib/libpython3.8.so.1.0
#13 0x00007ffff7b38b6c in  () at /usr/lib/libpython3.8.so.1.0
#14 0x00007ffff7b3c2e2 in PyObject_Call () at /usr/lib/libpython3.8.so.1.0
#15 0x00007ffff70b0988 in  () at /usr/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#16 0x00007ffff70b0dd1 in  () at /usr/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#17 0x00007ffff70b0f7d in  () at /usr/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#18 0x00007ffff70b371e in  () at /usr/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#19 0x00007ffff70b34ec in  () at /usr/lib/python3.8/site-packages/PyQt5/QtCore.abi3.so
#20 0x00007ffff27b47bb in  () at /usr/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#21 0x00007ffff6937762 in  () at /usr/lib/libQt5Core.so.5
#22 0x00007ffff1f63b83 in QAbstractButton::clicked(bool) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff1f6450c in  () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff1f65eb3 in  () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff1f66093 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff2773584 in  () at /usr/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#27 0x00007ffff1eb3c7e in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff2773e34 in  () at /usr/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#29 0x00007ffff1e72702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff1e79977 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff27a280f in  () at /usr/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#32 0x00007ffff69007ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#33 0x00007ffff1e7885e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib/libQt5Widgets.so.5
#34 0x00007ffff1ecc3b2 in  () at /usr/lib/libQt5Widgets.so.5
#35 0x00007ffff1ecf78f in  () at /usr/lib/libQt5Widgets.so.5
#36 0x00007ffff1e72702 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#37 0x00007ffff27a280f in  () at /usr/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#38 0x00007ffff69007ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#39 0x00007ffff2ff737c in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
#40 0x00007ffff2fccb4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#41 0x00007fffea9c3c8c in  () at /usr/lib/libQt5XcbQpa.so.5
#42 0x00007ffff5e6843c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#43 0x00007ffff5eb61d9 in  () at /usr/lib/libglib-2.0.so.0
#44 0x00007ffff5e67221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#45 0x00007ffff6959331 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#46 0x00007ffff68ff13c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#47 0x00007ffff69075c4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#48 0x00007ffff27a180f in  () at /usr/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#49 0x00007ffff7b2f1ea in PyCFunction_Call () at /usr/lib/libpython3.8.so.1.0
#50 0x00007ffff7b21bf4 in _PyObject_MakeTpCall () at /usr/lib/libpython3.8.so.1.0
#51 0x00007ffff7b1d4d8 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.8.so.1.0
#52 0x00007ffff7b29138 in _PyFunction_Vectorcall () at /usr/lib/libpython3.8.so.1.0
#53 0x00007ffff7b18b41 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.8.so.1.0
#54 0x00007ffff7b170c4 in _PyEval_EvalCodeWithName () at /usr/lib/libpython3.8.so.1.0
#55 0x00007ffff7bc8323 in PyEval_EvalCode () at /usr/lib/libpython3.8.so.1.0
#56 0x00007ffff7bd3b98 in  () at /usr/lib/libpython3.8.so.1.0
#57 0x00007ffff7bcddb3 in  () at /usr/lib/libpython3.8.so.1.0
#58 0x00007ffff7a8ca0b in PyRun_FileExFlags () at /usr/lib/libpython3.8.so.1.0
#59 0x00007ffff7a8c482 in PyRun_SimpleFileExFlags () at /usr/lib/libpython3.8.so.1.0
#60 0x00007ffff7be0a1a in Py_RunMain () at /usr/lib/libpython3.8.so.1.0
#61 0x00007ffff7bbcbd9 in Py_BytesMain () at /usr/lib/libpython3.8.so.1.0
#62 0x00007ffff7db0002 in __libc_start_main () at /usr/lib/libc.so.6
#63 0x000055555555504e in _start ()
```

I don't know the correct procedure to also build a debug version of carla and run that from a checkout. I'll report back if I figure that out.

**Comment by sjaehn** [comment]
Thanks for the bt. Indeed, I don't see anything from B.Harvestr in the bt. B.Harvestr doesn't use Qt. Maybe @falkTX knows more.

**Comment by falkTX** [comment]
The coredump from @mxmilkiib in the first post is 404.

But seems like a carla issue, will need to try the plugin.

**Comment by mxmilkiib** [comment]
Fixed the link, I had changed my username.
